/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function zolaBuild(rootDir: string, configFile: string, baseUrl: string | undefined | null, outputDir: string | undefined | null, force: boolean, includeDrafts: boolean): void
export function zolaInit(name: string, force: boolean): void
export function zolaCheck(rootDir: string, configFile: string, basePath: string | undefined | null, baseUrl: string | undefined | null, includeDrafts: boolean): void
export function zolaServe(rootDir: string, interface: string, interfacePort: number, outputDir: string | undefined | null, baseUrl: string, configFile: string, open: boolean, includeDrafts: boolean, fastRebuild: boolean, noPortAppend: boolean): void
export function zolaCommandParse(input: Array<string>): void
